spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      dialect: ${DB_DIALECT}
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  jwt:
    secret: QWxhZGRpbjpvcGVuIHNlc2FtZSBBbGFkZGluOiBvcGVuIHNlc2FtZSBCbGFkZGluOiBvcGVuIHNlc2FtZQ
    jwtExpirationMs: 315360000
